version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
    ports:
      - 27017:27017

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app

    depends_on:
      - mongodb
    ports:
      - 3000:3000
