export enum SettingKey {
  SimulationUpdate = 'simulationUpdate',
  MonitoringUpdate = 'monitoringUpdate',
  TripMinSpeed = 'tripMinSpeed',
  TripTime = 'tripTime',
  CloseEventDistance = 'closeEventDistance',
  NewPointDistance = 'newPointDistance',
  OutOfRangeLocation = 'outOfRangeLocation',
  MergePointDistance = 'mergePointDistance',
  HeightMinThreshold = 'heightMinThreshold',
  HeightMaxThreshold = 'heightMaxThreshold',
  ZigzagMaxThreshold = 'zigzagMaxThreshold',
  ZigzagMinThreshold = 'zigzagMinThreshold',
  EventLimitSpeed = 'eventLimitSpeed',
  PointsStatusSummaryPriority = 'pointsStatusSummaryPriority',
  CalendarTripsPriority = 'calendarTripsPriority',
  NewEventsPriority = 'newEventsPriority',
  PantographsPriority = 'pantographsPriority',
  DeviceOnTrainsPriority = 'deviceOnTrainsPriority',
  UserActivityPriority = 'userActivityPriority',
  TriggerAlarmsPriority = 'triggerAlarmsPriority',
  ReportingPriority = 'reportingPriority',
  ImportedEventsPriority = 'importedEventsPriority',
  RemoveEventThreshold = 'removeEventThreshold',
}
